name: Bug Report
description: Report a bug in Mini-RAG
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Index document with '...'
        3. Search for '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: If applicable, add error messages or log output
      render: shell

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI
        - HTTP API
        - Indexing
        - Search
        - Configuration
        - Compression
        - PDF Processing
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Mini-RAG Version
      description: What version of Mini-RAG are you running?
      placeholder: "v1.0.0 or commit hash"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using?
      placeholder: "go version output"

  - type: input
    id: ollama-version
    attributes:
      label: Ollama Version
      description: What version of Ollama are you using?
      placeholder: "ollama version output"

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your Mini-RAG configuration (remove sensitive information)
      render: json

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.