name: Question/Help
description: Ask a question or get help with Mini-RAG
title: "[Question]: "
labels: ["question", "help wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about using Mini-RAG? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does your question fall into?
      options:
        - Installation/Setup
        - Configuration
        - CLI Usage
        - HTTP API
        - Indexing Documents
        - Search Functionality
        - Performance
        - Troubleshooting
        - Development/Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background information.
      placeholder: What are you trying to accomplish? What have you tried so far?

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your Mini-RAG configuration (if relevant, remove sensitive information)
      render: json

  - type: input
    id: version
    attributes:
      label: Mini-RAG Version
      placeholder: "v1.0.0 or commit hash"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful.